// Regenerates `fixtures/ical/index.ts` from the committed `.ics` files.
//
// Why a generated module: Convex bundles with esbuild, which has no `?raw`
// loader, so a `.ics` file cannot be imported directly from `convex/`. The
// `.ics` files stay the source of truth (they are what a real feed looks like,
// and what a human reviews); this script mirrors them into a TS module the
// bundler can see. Run `node fixtures/ical/build.mjs` after editing any `.ics`.
import { readFileSync, writeFileSync } from "node:fs"

const here = new URL("./", import.meta.url)

const SOURCES = [
  { name: "canvasFeedIcs", path: "canvas-feed.ics" },
  { name: "genericIcs", path: "generic.ics" },
  { name: "conflictFeedIcs", path: "../changes/conflict/canvas-feed.ics" },
]

const escape = (text) =>
  text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${")

const body = SOURCES.map(({ name, path }) => {
  const text = readFileSync(new URL(path, here), "utf8")
  return `/** Generated from \`fixtures/ical/${path}\`. */\nexport const ${name} = \`${escape(text)}\`\n`
}).join("\n")

writeFileSync(
  new URL("index.ts", here),
  `// GENERATED by fixtures/ical/build.mjs — do not edit by hand.\n` +
    `// Edit the .ics files and re-run \`node fixtures/ical/build.mjs\`.\n\n` +
    body
)

console.log("wrote fixtures/ical/index.ts")
