// GENERATED by fixtures/ical/build.mjs — do not edit by hand.
// Edit the .ics files and re-run `node fixtures/ical/build.mjs`.

/** Generated from `fixtures/ical/canvas-feed.ics`. */
export const canvasFeedIcs = `BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//Instructure//Canvas//EN
X-WR-CALNAME:Fixture Student Canvas Feed
BEGIN:VEVENT
DTSTAMP:20260901T120000Z
UID:event-assignment-5101
DTSTART:20260915T035900Z
DTEND:20260915T035900Z
SUMMARY:Assignment 1: Sorting [CS201]
DESCRIPTION:Implement three comparison sorts and benchmark them. Submit a
 zip with your Java sources and the benchmark writeup\\; late work is accept
 ed for 48 hours at a 10% penalty.
URL:https://canvas.example.edu/courses/1002/assignments/5101
CLASS:PUBLIC
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20260901T120000Z
UID:event-assignment-5107
DTSTART:20261027T163000Z
DTEND:20261027T163000Z
SUMMARY:Midterm Exam [CS201]
DESCRIPTION:Online and proctored\\, in Gross Hall 103.
URL:https://canvas.example.edu/courses/1002/assignments/5107
CLASS:PUBLIC
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20260901T120000Z
UID:event-assignment-5201
DTSTART:20260914T035900Z
DTEND:20260914T035900Z
SUMMARY:Homework 1: Exploratory Data Analysis [STA210]
DESCRIPTION:Quarto document\\, knitted to PDF.
URL:https://canvas.example.edu/courses/1003/assignments/5201
CLASS:PUBLIC
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20260901T120000Z
UID:event-assignment-5006
DTSTART:20261023T171500Z
DTEND:20261023T171500Z
SUMMARY:Midterm Exam [BIO201]
DESCRIPTION:In class\\, Bio Sci 111. Covers chapters 1-9.
URL:https://canvas.example.edu/courses/1001/assignments/5006
CLASS:PUBLIC
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20260901T120000Z
UID:event-calendar-event-9001
DTSTART;TZID=America/New_York:20260908T101500
DTEND;TZID=America/New_York:20260908T113000
SUMMARY:BIO 201 Lecture [BIO201]
LOCATION:Biological Sciences 111
DESCRIPTION:Tuesday/Thursday lecture.
CLASS:PUBLIC
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20260901T120000Z
UID:event-calendar-event-9002
DTSTART;TZID=America/New_York:20260908T133000
DTEND;TZID=America/New_York:20260908T144500
SUMMARY:CS 201 Lecture [CS201]
LOCATION:Gross Hall 103
DESCRIPTION:Tuesday/Thursday lecture.
CLASS:PUBLIC
END:VEVENT
END:VCALENDAR
`

/** Generated from `fixtures/ical/generic.ics`. */
export const genericIcs = `BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//Example Study Group//Planner 1.0//EN
X-WR-CALNAME:Study Group + Deadlines
BEGIN:VEVENT
DTSTAMP:20261001T090000Z
UID:2026-outline@studygroup.example
DTSTART;VALUE=DATE:20261102
DTEND;VALUE=DATE:20261103
SUMMARY:Term paper outline [STA210]
DESCRIPTION:One page\\, thesis plus sources.
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20261001T090000Z
UID:2026-groupmeet@studygroup.example
DTSTART;TZID=America/New_York:20261103T190000
DTEND;TZID=America/New_York:20261103T203000
SUMMARY:Stats study group
LOCATION:Perkins 218
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20261001T090000Z
UID:2026-scholarship@financialaid.example
DTSTART:20261120T045959Z
SUMMARY:Scholarship application deadline
DESCRIPTION:Upload transcript\\, essay\\, and two letters through the portal
 . Nothing is accepted after midnight.
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20261001T090000Z
UID:legacy-import-88@planner.example
DTSTART:20261012T035900Z
SUMMARY:Homework 3: Multiple Regression
DESCRIPTION:Imported from an older planner\\; duplicates the Canvas item.
END:VEVENT
END:VCALENDAR
`

/** Generated from `fixtures/ical/../changes/conflict/canvas-feed.ics`. */
export const conflictFeedIcs = `BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//Instructure//Canvas//EN
X-WR-CALNAME:Fixture Student Canvas Feed
BEGIN:VEVENT
DTSTAMP:20260901T120000Z
UID:event-assignment-5101
DTSTART:20260916T035900Z
DTEND:20260916T035900Z
SUMMARY:Assignment 1: Sorting [CS201]
DESCRIPTION:Implement three comparison sorts and benchmark them. Submit a
 zip with your Java sources and the benchmark writeup\\; late work is accept
 ed for 48 hours at a 10% penalty.
URL:https://canvas.example.edu/courses/1002/assignments/5101
CLASS:PUBLIC
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20260901T120000Z
UID:event-assignment-5107
DTSTART:20261027T163000Z
DTEND:20261027T163000Z
SUMMARY:Midterm Exam [CS201]
DESCRIPTION:Online and proctored\\, in Gross Hall 103.
URL:https://canvas.example.edu/courses/1002/assignments/5107
CLASS:PUBLIC
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20260901T120000Z
UID:event-assignment-5201
DTSTART:20260914T035900Z
DTEND:20260914T035900Z
SUMMARY:Homework 1: Exploratory Data Analysis [STA210]
DESCRIPTION:Quarto document\\, knitted to PDF.
URL:https://canvas.example.edu/courses/1003/assignments/5201
CLASS:PUBLIC
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20260901T120000Z
UID:event-assignment-5006
DTSTART:20261023T171500Z
DTEND:20261023T171500Z
SUMMARY:Midterm Exam [BIO201]
DESCRIPTION:In class\\, Bio Sci 111. Covers chapters 1-9.
URL:https://canvas.example.edu/courses/1001/assignments/5006
CLASS:PUBLIC
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20260901T120000Z
UID:event-calendar-event-9001
DTSTART;TZID=America/New_York:20260908T101500
DTEND;TZID=America/New_York:20260908T113000
SUMMARY:BIO 201 Lecture [BIO201]
LOCATION:Biological Sciences 111
DESCRIPTION:Tuesday/Thursday lecture.
CLASS:PUBLIC
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20260901T120000Z
UID:event-calendar-event-9002
DTSTART;TZID=America/New_York:20260908T133000
DTEND;TZID=America/New_York:20260908T144500
SUMMARY:CS 201 Lecture [CS201]
LOCATION:Gross Hall 103
DESCRIPTION:Tuesday/Thursday lecture.
CLASS:PUBLIC
END:VEVENT
END:VCALENDAR
`
